# Generated by Django 3.2 on 2024-01-02 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('lender', 'Lender'), ('borrower', 'Borrower')], default='lender', max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('created_by_id', models.ForeignKey(db_column='created_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finappmodel.userprofile')),
                ('updated_by_id', models.ForeignKey(db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finappmodel.userprofile')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
