# Generated by Django 3.2 on 2024-01-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finappmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=255)),
                ('country_id', models.IntegerField(null=True)),
                ('created_by_id', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finappmodel.userprofile')),
                ('updated_by_id', models.ForeignKey(db_column='updated_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finappmodel.userprofile')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_accesstoken',
            },
        ),
    ]
