# Generated by Django 3.2 on 2024-01-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappmodel', '0002_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_by_id',
        ),
    ]
