# Generated by Django 3.2 on 2024-01-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappmodel', '0003_auto_20240124_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='country_id',
        ),
    ]
