# Generated by Django 3.2 on 2024-01-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappmodel', '0004_remove_accesstoken_country_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accesstoken',
            table='accesstoken',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
