# Generated by Django 3.2 on 2024-02-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappmodel', '0006_auto_20240206_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='india', max_length=100),
            preserve_default=False,
        ),
    ]
